# Generated by Django 5.2.7 on 2025-11-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
